TypeError: destroy is not a function
    at call (.syntest/tests/tempTest.spec.js:10:39)
    at tryCatch (.syntest/tests/tempTest.spec.js:2:1)
    at Generator._invoke (.syntest/tests/tempTest.spec.js:2:1)
    at Generator.next (.syntest/tests/tempTest.spec.js:2:1)
    at asyncGeneratorStep (.syntest/tests/tempTest.spec.js:2:1)
    at _next (.syntest/tests/tempTest.spec.js:2:1)
    at /local/tmp/oliverphil/4167921.1/syntest-crash-reproduction/.syntest/tests/tempTest.spec.js:2:1
    at new Promise (<anonymous>)
    at Context.<anonymous> (.syntest/tests/tempTest.spec.js:2:1)
    at processImmediate (node:internal/timers:476:21)
