Error: spawn git ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at executeCmd (lib/util/cmd.js:61:22)
    at PThrottler._processEntry (node_modules/p-throttler/index.js:89:25)
    at Promise.apply (node_modules/p-throttler/node_modules/q/q.js:1122:26)
    at Promise.promise.promiseDispatch (node_modules/p-throttler/node_modules/q/q.js:752:41)
    at node_modules/p-throttler/node_modules/q/q.js:1337:14
    at flush (node_modules/p-throttler/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at Array.reduce (native)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at Function.GitResolver.tags (lib/core/resolvers/GitResolver.js:299:6)
    at GitFsResolver.GitResolver._findResolution (lib/core/resolvers/GitResolver.js:156:14)
    at GitFsResolver.GitResolver._resolve (lib/core/resolvers/GitResolver.js:66:17)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at GitFsResolver.Resolver.resolve (lib/core/resolvers/Resolver.js:83:6)
    at Context.<anonymous> (test/core/resolvers/gitFsResolver.js:74:22)