AssertionError: expected [Function] to not throw an error but 'YAMLException: duplicated mapping key at line 92, column 5:\n        no-console: 0\n        ^' was thrown
  {
    ruleId: null,
    fatal: true,
    severity: 2,
    source: '        foo={super}',
    message: 'Parsing error: Unexpected token }',
    line: 5,
    column: 19
  }
]
    at testValidTemplate (lib/testers/rule-tester.js:415:20)
    at Context.<anonymous> (lib/testers/rule-tester.js:545:25)
    at processImmediate (internal/timers.js:461:21)