TypeError: Unknown encoding: URDA3hzyX36b4sUbH5DnonODf4Vz7bC57QJBAio32ImmsVlnnOJNalF0UgK
    at new NodeError (node:internal/errors:399:5)
    at fromString (node:buffer:500:13)
    at Function.from (node:buffer:314:12)
    at Readable.push (.syntest/instrumented/crashes/atom/atom-22894/node_modules/readable-stream/lib/_stream_readable.js:12821:24)
    at _callee$ (.syntest/tests/tempTest.spec.js:6:45)
    at tryCatch (.syntest/tests/tempTest.spec.js:1:129)
    at Generator.<anonymous> (.syntest/tests/tempTest.spec.js:1:129)
    at Generator.next (.syntest/tests/tempTest.spec.js:1:129)
    at resolve (.syntest/tests/tempTest.spec.js:2:1)
    at _next (.syntest/tests/tempTest.spec.js:2:1)
    at gen (.syntest/tests/tempTest.spec.js:2:1)
    at new Promise (<anonymous>)
    at Context.<anonymous> (.syntest/tests/tempTest.spec.js:2:1)
    at processImmediate (node:internal/timers:476:21) {
